"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { ttuConfig } from "@/config/ttu";
import { makeBackup, readBackup } from "@/domain/backup";
import { type AppSettings, type ClassSession, type Course, type DayCode, type StudentProfile } from "@/domain/models";
import { dayNames, expandRoom, formatArabicTime, hasConflict, makeSessions, orderedDays, sortSessions } from "@/domain/schedule";
import { generateIcs } from "@/domain/calendar";
import type { AppSnapshot } from "@/repositories/schedule-repository";
import { LocalScheduleRepository } from "@/storage/local-repository";

const repo = new LocalScheduleRepository();
type CourseForm = { name: string; kind: "lecture" | "lab" | "unspecified"; days: DayCode[]; startsAt: string; endsAt: string; room: string; reminder: boolean; minutesBefore: number };
const navigation = [{ href: "/", label: "الرئيسية" }, { href: "/schedule", label: "جدولي" }, { href: "/calendar", label: "التقويم" }, { href: "/settings", label: "الإعدادات" }];

export function MurattabApp() {
  const pathname = usePathname(); const [data, setData] = useState<AppSnapshot | null>(null); const [loadError, setLoadError] = useState<string | null>(null); const [showSplash, setShowSplash] = useState(false); const [online, setOnline] = useState(true); const [modal, setModal] = useState<"course" | "restore" | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const refresh = async () => setData(await repo.snapshot());
  const dismissSplash = () => { sessionStorage.setItem("murattab-splash", "1"); setShowSplash(false); };
  useEffect(() => {
    void repo.snapshot().then((snapshot) => setData(snapshot)).catch((error: unknown) => { console.error("Murattab storage error", error); setLoadError(error instanceof Error ? error.message : "تعذر فتح التخزين المحلي"); });
    if (process.env.NODE_ENV === "production" && "serviceWorker" in navigator) void navigator.serviceWorker.register("/sw.js");
    const update = () => setOnline(navigator.onLine);
    addEventListener("online", update); addEventListener("offline", update);
    if (!sessionStorage.getItem("murattab-splash")) {
      // This state is derived from session storage only after hydration, avoiding a server/client mismatch.
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setShowSplash(true);
      const id = setTimeout(dismissSplash, 4000);
      return () => { clearTimeout(id); removeEventListener("online", update); removeEventListener("offline", update); };
    }
    return () => { removeEventListener("online", update); removeEventListener("offline", update); };
  }, []);
  const active = navigation.find((item) => item.href === pathname)?.href ?? "/";
  const content = !data ? <div className="empty">{loadError ? `تعذر فتح التخزين المحلي: ${loadError}` : "جارٍ تجهيز بياناتك المحلية…"}</div> : !data.profile ? <Onboarding onComplete={async (profile, settings, term) => { await repo.bootstrap(profile, term, settings); await refresh(); }} /> : <Dashboard data={data} pathname={pathname} openCourse={() => setModal("course")} openRestore={() => setModal("restore")} refresh={refresh} notify={setNotice} />;
  return <><main className="app" data-theme={data?.settings.theme === "dark" ? "dark" : undefined}><header className="topbar"><Link href="/" className="brand" aria-label="مرتب، الرئيسية"><span className="brand-mark" aria-hidden="true" />مرتب</Link><div className={`status ${online ? "online" : ""}`}>{online ? "متصل" : "دون اتصال"}</div><nav className="nav" aria-label="التنقل الرئيسي">{navigation.map((item) => <Link key={item.href} href={item.href} aria-current={active === item.href ? "page" : undefined}>{item.label}</Link>)}</nav></header>{content}</main><nav className="bottom-nav" aria-label="التنقل الرئيسي للهاتف">{navigation.map((item) => <Link key={item.href} href={item.href} aria-current={active === item.href ? "page" : undefined}>{item.label}</Link>)}</nav>{showSplash && <Splash onDismiss={dismissSplash} />} {modal === "course" && data && <CourseDialog data={data} close={() => setModal(null)} saved={async () => { setModal(null); await refresh(); }} />} {modal === "restore" && data && <RestoreDialog close={() => setModal(null)} restored={async () => { await refresh(); setModal(null); }} />} {notice && <div className="dialog-backdrop" role="alertdialog" aria-modal="true"><div className="dialog"><p>{notice}</p><button className="button" onClick={() => setNotice(null)}>حسنًا</button></div></div>}</>;
}

function Splash({ onDismiss }: { onDismiss: () => void }) {
  const videoRef = useRef<HTMLVideoElement>(null); const [reducedMotion, setReducedMotion] = useState(false);
  useEffect(() => { const query = matchMedia("(prefers-reduced-motion: reduce)"); const update = () => setReducedMotion(query.matches); update(); query.addEventListener("change", update); const video = videoRef.current; return () => { query.removeEventListener("change", update); if (video) { video.pause(); video.removeAttribute("src"); video.load(); } }; }, []);
  return <div className="splash" role="dialog" aria-modal="true" aria-label="شاشة بدء مرتب"><div>{reducedMotion ? <div className="splash-poster"><span className="brand-mark" aria-hidden="true" /></div> : <video ref={videoRef} autoPlay muted playsInline preload="auto" poster="/icons/icon.svg" src="/brand/splash.mp4" aria-label="فيديو هوية مرتب" onCanPlay={(event) => { void event.currentTarget.play().catch(() => undefined); }} />}<h1>مرتب</h1><p>جدولك الجامعي، أوضح وأقرب إليك.</p><button className="button secondary splash-skip" onClick={onDismiss}>تخطي الفيديو</button></div></div>;
}

function Onboarding({ onComplete }: { onComplete: (profile: StudentProfile, settings: AppSettings, term: { id: string; name: string; startsOn: string; endsOn: string; isCurrent: boolean }) => Promise<void> }) {
  const { register, handleSubmit, watch, formState: { errors, isSubmitting } } = useForm<{ name: string; facultyId: string; majorId: string }>({ defaultValues: { facultyId: ttuConfig.faculties[0].id, majorId: ttuConfig.majors[0].id } }); const facultyId = watch("facultyId"); const majors = ttuConfig.majors.filter((major) => major.facultyId === facultyId);
  return <section className="onboarding card"><p className="eyebrow">مرحبًا بك في مرتب</p><h1>لنرتّب فصلك الدراسي</h1><p className="muted">هذه البيانات تبقى على جهازك. قوائم الكليات والتخصصات الحالية مخصّصة للتطوير حتى اعتماد بيانات الجامعة الرسمية.</p><form className="form" onSubmit={handleSubmit(async (values) => { const profile = { id: crypto.randomUUID(), name: values.name.trim(), universityId: "ttu", facultyId: values.facultyId, majorId: values.majorId, createdAt: new Date().toISOString() }; const term = { id: crypto.randomUUID(), name: "الفصل الحالي", startsOn: "2026-09-01", endsOn: "2026-12-31", isCurrent: true }; await onComplete(profile, { id: "settings", theme: "system", onboardingComplete: true, splashShown: true, activeTermId: term.id, guideSeen: true, schemaVersion: 1 }, term); })}><label className="field">الاسم<input autoFocus {...register("name", { required: "اكتب اسمك أولًا", validate: (value) => value.trim().length > 0 || "اكتب اسمك أولًا" })} />{errors.name && <span role="alert">{errors.name.message}</span>}</label><label className="field">الكلية<select {...register("facultyId")}>{ttuConfig.faculties.map((faculty) => <option value={faculty.id} key={faculty.id}>{faculty.name}</option>)}</select></label><label className="field">التخصص<select {...register("majorId")}>{majors.map((major) => <option value={major.id} key={major.id}>{major.name}</option>)}</select></label><button className="button" disabled={isSubmitting}>{isSubmitting ? "جارٍ الحفظ…" : "ابدأ مع مرتب"}</button></form></section>;
}

function Dashboard({ data, pathname, openCourse, openRestore, refresh, notify }: { data: AppSnapshot; pathname: string; openCourse: () => void; openRestore: () => void; refresh: () => Promise<void>; notify: (value: string) => void }) {
  if (pathname === "/schedule") return <ScheduleView data={data} openCourse={openCourse} refresh={refresh} notify={notify} />;
  if (pathname === "/calendar") return <CalendarView data={data} />;
  if (pathname === "/settings") return <SettingsView data={data} openRestore={openRestore} refresh={refresh} notify={notify} />;
  const todayCode = orderedDays[new Date().getDay() === 6 ? 0 : new Date().getDay()] ?? "ح"; const todaySessions = sortSessions(data.sessions.filter((session) => session.day === todayCode)); const sessions = todaySessions.length ? todaySessions : sortSessions(data.sessions); const next = sessions.find((session) => session.endsAt > new Date().toTimeString().slice(0, 5)) ?? sessions[0]; const course = data.courses.find((item) => item.id === next?.courseId);
  return <><section className="hero"><div className="card"><p className="eyebrow">أهلًا، {data.profile?.name}</p><h1>جدولك في مكانه الصحيح.</h1><p className="muted">أضف جلساتك يدويًا، ثم اعرضها بتفاصيل أوضح على يومك وتقويمك.</p><button className="button" onClick={openCourse}>إضافة مادة يدويًا</button></div><div className="next-card"><p className="eyebrow">المحاضرة القادمة</p>{next && course ? <><h2>{course.name}</h2><p>{formatArabicTime(next.startsAt)} — {formatArabicTime(next.endsAt)}</p><p className="muted">{next.room.label}</p></> : <><h2>لا توجد محاضرة قادمة</h2><p className="muted">أضف جدولك لتظهر محاضرات اليوم هنا.</p></>}</div></section><section><div className="section-head"><h2>بقية اليوم · {dayNames[todayCode]}</h2><Link className="button secondary" href="/schedule">عرض جدولي</Link></div><SessionList sessions={sessions} courses={data.courses} empty="لا توجد جلسات لهذا اليوم." /></section></>;
}

function SessionList({ sessions, courses, empty }: { sessions: ClassSession[]; courses: Course[]; empty: string }) { if (!sessions.length) return <div className="card empty">{empty}</div>; return <div className="card">{sessions.map((session) => { const course = courses.find((item) => item.id === session.courseId); return <article className="session" key={session.id}><div><span className={`kind ${session.kind === "lab" ? "lab" : ""}`}>{session.kind === "lecture" ? "نظري" : session.kind === "lab" ? "عملي" : "غير محدد"}</span><h3>{course?.name ?? "مادة غير معروفة"}</h3><p className="muted">{session.room.label}</p></div><div className="time">{formatArabicTime(session.startsAt)}<br />{formatArabicTime(session.endsAt)}</div></article>; })}</div>; }

function ScheduleView({ data, openCourse, refresh, notify }: { data: AppSnapshot; openCourse: () => void; refresh: () => Promise<void>; notify: (value: string) => void }) { const [day, setDay] = useState<DayCode>("ح"); const sessions = sortSessions(data.sessions.filter((item) => item.day === day)); const exportIcs = () => { const term = data.terms.find((item) => item.id === data.settings.activeTermId); if (!term) return; const blob = new Blob([generateIcs(data.courses, data.sessions, term)], { type: "text/calendar" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "murattab-schedule.ics"; link.click(); URL.revokeObjectURL(url); }; return <section><div className="section-head"><div><p className="eyebrow">جدولي</p><h1>أسبوعك الدراسي</h1></div><button className="button" onClick={openCourse}>إضافة مادة</button></div><div className="tabs" role="tablist" aria-label="أيام الأسبوع">{orderedDays.map((code) => <button role="tab" aria-selected={day === code} key={code} onClick={() => setDay(code)}>{dayNames[code]}</button>)}</div><SessionList sessions={sessions} courses={data.courses} empty={`لا توجد جلسات يوم ${dayNames[day]}.`} />{data.courses.length > 0 && <div className="card" style={{ marginTop: 18 }}><div className="section-head"><h2>إدارة المواد</h2><button className="button secondary" onClick={exportIcs}>تصدير التقويم ICS</button></div>{data.courses.map((course) => <div className="setting" key={course.id}><span>{course.name}</span><button className="button danger" onClick={async () => { if (confirm(`حذف مادة ${course.name} وجميع جلساتها؟`)) { await repo.deleteCourse(course.id); await refresh(); notify("تم حذف المادة."); } }}>حذف</button></div>)}</div>}</section>; }

function CalendarView({ data }: { data: AppSnapshot }) { const [selected, setSelected] = useState(1); const days = Array.from({ length: 30 }, (_, index) => index + 1); const sessionForDate = (date: number) => data.sessions.filter((session) => ((date - 1) % 7) === orderedDays.indexOf(session.day)); return <section><p className="eyebrow">التقويم</p><h1>الفصل الحالي</h1><div className="card"><div className="month" role="grid" aria-label="تقويم شهري">{days.map((date) => { const count = sessionForDate(date).length; return <button className={`day-cell ${count ? "has-session" : ""} ${selected === date ? "selected" : ""}`} key={date} onClick={() => setSelected(date)} aria-label={`${date}، ${count} جلسات`}>{date}{count > 0 && <small> · {count} جلسة</small>}</button>; })}</div></div><div className="section-head"><h2>جلسات اليوم {selected}</h2></div><SessionList sessions={sessionForDate(selected)} courses={data.courses} empty="لا توجد جلسات في هذا اليوم." /></section>; }

function SettingsView({ data, openRestore, refresh, notify }: { data: AppSnapshot; openRestore: () => void; refresh: () => Promise<void>; notify: (value: string) => void }) { const update = async (patch: Partial<AppSettings>) => { await repo.saveSettings({ ...data.settings, ...patch }); await refresh(); }; const download = () => { const blob = new Blob([JSON.stringify(makeBackup(data), null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "murattab-backup.json"; link.click(); URL.revokeObjectURL(url); }; return <section><p className="eyebrow">الإعدادات</p><h1>إعداداتك المحلية</h1><div className="card settings"><div className="setting"><div><h2>المظهر</h2><p className="muted">اختر ما يناسبك.</p></div><select aria-label="المظهر" value={data.settings.theme} onChange={(event) => void update({ theme: event.target.value as AppSettings["theme"] })}><option value="system">إعداد الجهاز</option><option value="light">فاتح</option><option value="dark">داكن</option></select></div><div className="setting"><div><h2>التنبيهات والتقويم</h2><p className="muted">التنبيهات داخل التطبيق فقط؛ لا توجد تنبيهات Push مجدولة.</p></div></div><div className="setting"><div><h2>الفصل الحالي</h2><p className="muted">{data.terms.find((term) => term.id === data.settings.activeTermId)?.name ?? "غير محدد"}</p></div></div><div className="setting"><div><h2>الملف المحلي</h2><p className="muted">{data.profile?.name} · {ttuConfig.name}</p></div></div><div className="setting"><div><h2>النسخة الاحتياطية</h2><p className="muted">تصدير واستعادة بياناتك المحلية بصيغة JSON.</p></div><div><button className="button secondary" onClick={download}>تصدير</button><button className="button ghost" onClick={openRestore}>استعادة</button></div></div><div className="setting"><div><h2>الدليل الإرشادي</h2><p className="muted">يمكنك إعادة التشغيل عند الحاجة.</p></div><button className="button secondary" onClick={() => notify("سيظهر الدليل الإرشادي في أول شاشة مستقبلية؛ تم تجهيز حالة إعادة التشغيل.")}>إعادة التشغيل</button></div><div className="setting"><div><h2>إدارة البيانات</h2><p className="muted">يحذف هذا الإجراء كل بيانات التطبيق من هذا الجهاز.</p></div><button className="button danger" onClick={async () => { if (confirm("هل أنت متأكد؟ سيُحذف كل جدولك وملفك المحلي.")) { await repo.clear(); await refresh(); notify("تم حذف البيانات المحلية."); } }}>حذف البيانات</button></div><div className="setting"><div><h2>الخصوصية والإصدار</h2><p className="muted">مرتب 0.1.0 · لا تُرسل بياناتك إلى خادم.</p></div></div></div></section>; }

function CourseDialog({ data, close, saved }: { data: AppSnapshot; close: () => void; saved: () => Promise<void> }) {
  const { register, handleSubmit, watch, formState: { errors, isSubmitting } } = useForm<CourseForm>({ defaultValues: { kind: "lecture", days: [], startsAt: "08:00", endsAt: "09:00", room: "", reminder: true, minutesBefore: 10 } });
  return <div className="dialog-backdrop" role="dialog" aria-modal="true" aria-labelledby="add-title"><div className="dialog"><div className="section-head"><h2 id="add-title">إضافة مادة يدويًا</h2><button className="button ghost" aria-label="إغلاق" onClick={close}>إغلاق</button></div><form className="form" onSubmit={handleSubmit(async (values) => {
    const courseId = crypto.randomUUID(); const termId = data.settings.activeTermId ?? data.terms[0]?.id; if (!termId) return;
    const sessions = makeSessions({ courseId, days: values.days, startsAt: values.startsAt, endsAt: values.endsAt, room: expandRoom(values.room), kind: values.kind });
    const conflicts = sessions.flatMap((session) => data.sessions.filter((item) => hasConflict(session, [item])));
    if (conflicts.length && !confirm("يوجد تعارض زمني مع جلسة أخرى. هل تريد الحفظ رغم ذلك؟")) return;
    await repo.saveCourse({ id: courseId, termId, name: values.name.trim(), reminder: { enabled: values.reminder, minutesBefore: Number(values.minutesBefore) }, createdAt: new Date().toISOString() }, sessions); await saved();
  })}><label className="field">اسم المادة<input autoFocus {...register("name", { required: "اسم المادة مطلوب", validate: (value) => value.trim().length > 0 || "اسم المادة مطلوب" })} />{errors.name && <span role="alert">{errors.name.message}</span>}</label><label className="field">النوع<select {...register("kind")}><option value="lecture">نظري</option><option value="lab">عملي</option><option value="unspecified">غير محدد</option></select></label><fieldset className="field"><legend>الأيام</legend><div className="check-grid">{orderedDays.map((day) => <label key={day}><input type="checkbox" value={day} {...register("days", { validate: (value) => value.length > 0 || "اختر يومًا واحدًا على الأقل" })} /> {dayNames[day]}</label>)}</div>{errors.days && <span role="alert">{errors.days.message}</span>}</fieldset><div className="grid"><label className="field">وقت البداية<input type="time" {...register("startsAt")} /></label><label className="field">وقت النهاية<input type="time" {...register("endsAt", { validate: (value) => value > watch("startsAt") || "يجب أن يأتي وقت النهاية بعد البداية" })} /></label></div><label className="field">القاعة أو Online<input placeholder="مثال: 207 م أو Online" {...register("room", { required: "اكتب القاعة أو Online" })} />{errors.room && <span role="alert">{errors.room.message}</span>}</label><label className="field">التنبيه قبل المحاضرة (دقائق)<input type="number" min="0" max="10080" {...register("minutesBefore", { valueAsNumber: true })} /></label><label><input type="checkbox" {...register("reminder")} /> تفعيل تنبيه داخل التطبيق</label><button className="button" disabled={isSubmitting}>{isSubmitting ? "جارٍ الحفظ…" : "حفظ المادة"}</button></form></div></div>;
}

function RestoreDialog({ close, restored }: { close: () => void; restored: () => Promise<void> }) { const [candidate, setCandidate] = useState<ReturnType<typeof readBackup>["data"] | null>(null); const [error, setError] = useState(""); return <div className="dialog-backdrop" role="dialog" aria-modal="true"><div className="dialog"><h2>استعادة نسخة احتياطية</h2><input type="file" accept="application/json" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; const result = readBackup(JSON.parse(await file.text())); if (result.success) { setCandidate(result.data); setError(""); } else setError("ملف النسخة الاحتياطية غير صالح أو لا يتوافق مع إصدار مرتب."); }} />{error && <p role="alert">{error}</p>}{candidate && <><p>سيتم استبدال البيانات الحالية: {candidate.courses.length} مادة و{candidate.sessions.length} جلسة.</p><button className="button warning" onClick={async () => { await repo.replace(candidate); await restored(); }}>تأكيد الاستبدال</button></>}<button className="button ghost" onClick={close}>إلغاء</button></div></div>; }
