import { AppSettingsSchema, type AppSettings, type StudentProfile, type Course, type ClassSession } from "@/domain/models";
import type { AppSnapshot, ScheduleRepository } from "@/repositories/schedule-repository";
import { db } from "./db";

export const initialSettings: AppSettings = { id: "settings", theme: "system", onboardingComplete: false, splashShown: false, activeTermId: null, guideSeen: false, schemaVersion: 1 };
export class LocalScheduleRepository implements ScheduleRepository {
  private profiles = db.table<StudentProfile, string>("profiles"); private settings = db.table<AppSettings, string>("settings"); private terms = db.table<import("@/domain/models").AcademicTerm, string>("terms"); private courses = db.table<Course, string>("courses"); private sessions = db.table<ClassSession, string>("sessions");
  private key = "murattab-fallback-v1";
  private fallback(): AppSnapshot { if (typeof localStorage === "undefined") return { profile: null, settings: initialSettings, terms: [], courses: [], sessions: [] }; const raw = localStorage.getItem(this.key); if (!raw) return { profile: null, settings: initialSettings, terms: [], courses: [], sessions: [] }; return JSON.parse(raw) as AppSnapshot; }
  private saveFallback(snapshot: AppSnapshot) { localStorage.setItem(this.key, JSON.stringify(snapshot)); }
  private async dexieSnapshot(): Promise<AppSnapshot> { const settings = AppSettingsSchema.parse((await this.settings.get("settings")) ?? initialSettings); return { profile: (await this.profiles.toArray())[0] ?? null, settings, terms: await this.terms.toArray(), courses: await this.courses.toArray(), sessions: await this.sessions.toArray() }; }
  async snapshot(): Promise<AppSnapshot> { return this.fallback(); }
  async saveProfile(profile: StudentProfile) { const next = { ...await this.snapshot(), profile }; this.saveFallback(next); void this.profiles.put(profile); }
  async bootstrap(profile: StudentProfile, term: import("@/domain/models").AcademicTerm, settings: AppSettings) { const next = { profile, settings, terms: [term], courses: [], sessions: [] }; this.saveFallback(next); void db.transaction("rw", this.profiles, this.terms, this.settings, async () => { await this.profiles.put(profile); await this.terms.put(term); await this.settings.put(AppSettingsSchema.parse(settings)); }); }
  async saveCourse(course: Course, sessions: ClassSession[]) { const current = await this.snapshot(); this.saveFallback({ ...current, courses: [...current.courses.filter((item) => item.id !== course.id), course], sessions: [...current.sessions.filter((item) => item.courseId !== course.id), ...sessions] }); void db.transaction("rw", this.courses, this.sessions, async () => { await this.courses.put(course); await this.sessions.bulkPut(sessions); }); }
  async deleteCourse(courseId: string) { const current = await this.snapshot(); this.saveFallback({ ...current, courses: current.courses.filter((item) => item.id !== courseId), sessions: current.sessions.filter((item) => item.courseId !== courseId) }); void db.transaction("rw", this.courses, this.sessions, async () => { await this.courses.delete(courseId); await this.sessions.where("courseId").equals(courseId).delete(); }); }
  async saveSettings(settings: AppSettings) { const current = await this.snapshot(); this.saveFallback({ ...current, settings: AppSettingsSchema.parse(settings) }); void this.settings.put(AppSettingsSchema.parse(settings)); }
  async replace(snapshot: AppSnapshot) { this.saveFallback(snapshot); void db.transaction("rw", this.profiles, this.settings, this.terms, this.courses, this.sessions, async () => { await Promise.all([this.profiles.clear(), this.settings.clear(), this.terms.clear(), this.courses.clear(), this.sessions.clear()]); if (snapshot.profile) await this.profiles.put(snapshot.profile); await this.settings.put(snapshot.settings); await this.terms.bulkPut(snapshot.terms); await this.courses.bulkPut(snapshot.courses); await this.sessions.bulkPut(snapshot.sessions); }); }
  async clear() { this.saveFallback({ profile: null, settings: initialSettings, terms: [], courses: [], sessions: [] }); void Promise.all([this.profiles.clear(), this.settings.clear(), this.terms.clear(), this.courses.clear(), this.sessions.clear()]); }
}
